Areas/Admin/Controllers/DanhMucController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebDatMonAn.Models;
using WebDatMonAn.Repository;

namespace WebDatMonAn.Area.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(AuthenticationSchemes = "AdminScheme")]
    public class DanhMucController : Controller
    {
        private readonly DataContext _dataContext;
        private readonly INotyfService _notyfService;

        public DanhMucController(DataContext dataContext, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _dataContext = dataContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            _notyfService.Success("Truy cập thành công!");
            var danhmuc = _dataContext.DanhMucs.OrderByDescending(c => c.MaDanhMuc).ToList();
            return View(danhmuc);
        }

        [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DanhMucModel danhMuc)
        {
            danhMuc.SlugDanhMuc = danhMuc.TenDanhMuc.Replace(" ", "-");
            var tendanhmuc = await _dataContext.DanhMucs.FirstOrDefaultAsync(p => p.TenDanhMuc == danhMuc.TenDanhMuc);
            if (tendanhmuc != null)
            {
                _notyfService.Error("Danh mục đã có trong đã tồn tại!");
                return View(danhMuc);
            }
            _dataContext.Add(danhMuc);
            await _dataContext.SaveChangesAsync();
            _notyfService.Success("Thêm mới danh mục thành công!");
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int Id)
        {
            var danhmuc = await _dataContext.DanhMucs.FindAsync(Id);
            if (danhmuc == null)
            {
                return NotFound(); // Return 404 if not found
            }
            return View(danhmuc);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(DanhMucModel danhmuc)
        {
            danhmuc.SlugDanhMuc = danhmuc.TenDanhMuc.Replace(" ", "-");
            var tendanhmuc = await _dataContext.DanhMucs.FirstOrDefaultAsync(p => p.TenDanhMuc == danhmuc.TenDanhMuc);
            var exists_category = await _dataContext.DanhMucs.FindAsync(danhmuc.MaDanhMuc);
            if (tendanhmuc != null && tendanhmuc.MaDanhMuc != danhmuc.MaDanhMuc)
            {
                _notyfService.Error("Danh mục đã có trong đã tồn tại!");
                return View(danhmuc);
            }
            if (exists_category == null)
            {
                return NotFound(); 
            }
            exists_category.TenDanhMuc = danhmuc.TenDanhMuc;
            exists_category.MoTa = danhmuc.MoTa;
            exists_category.TrangThai = danhmuc.TrangThai;
            _dataContext.Update(exists_category);
            await _dataContext.SaveChangesAsync();
            _notyfService.Success("Cập nhật danh mục thành công!");
            return RedirectToAction("Index");
        }

        
        public async Task<IActionResult> Delete(int Id)
        {
            var danhMuc = await _dataContext.DanhMucs.FindAsync(Id);
            if (danhMuc == null)
            {
                return NotFound(); 
            }
            _dataContext.DanhMucs.Remove(danhMuc);
            await _dataContext.SaveChangesAsync();
            _notyfService.Success("Xóa danh mục thành công!");
            return RedirectToAction("Index");
        }
    }
}

Controllers/DanhMucController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebDatMonAn.Models;
using WebDatMonAn.Repository;
using X.PagedList;

namespace WebDatMonAn.Controllers
{

    public class DanhMucController : Controller
    {
        private readonly DataContext _dataContext;
        public DanhMucController(DataContext dataContext)
        {
            _dataContext = dataContext;
        }
        public async Task<IActionResult> Index(string Slug = "", int? page = 1)
        {
            int pageSize = 4;
            int pageNumber = (page ?? 1);

            DanhMucModel danhmuc = _dataContext.DanhMucs.Where(c => c.SlugDanhMuc == Slug).FirstOrDefault();
            if (danhmuc == null) return RedirectToAction("Index");

            var monantheodanhmuc = _dataContext.MonAns
                .Include(c => c.DanhMuc)
                .Where(p => p.MaDanhMuc == danhmuc.MaDanhMuc)
                .OrderByDescending(p => p.MaDanhMuc);

            var pagedMonan = await monantheodanhmuc.ToPagedListAsync(pageNumber, pageSize);

            return View("~/Views/Home/Tatcamonan.cshtml", pagedMonan);
        }

    }
}

Areas/Admin/Views/DanhMuc/Create.cshtml
@model DanhMucModel
@{
    ViewData["title"] = "Thêm mới  Danh mục";
}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 col-12 mx-auto">
            <div class="card mt-5">
                <div class="card-header">
                    <h3>Thêm mới Danh mục</h3>
                </div>
                <div class="card-body">
                    <form asp-action="Create" asp-controller="DanhMuc" method="post">
                        <input type="hidden" asp-for="MaDanhMuc" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="form-label">Tên Danh mục</label>
                            <input asp-for="TenDanhMuc" type="text" class="form-control" />
                            <span asp-validation-for="TenDanhMuc" class="text-danger" />
                        </div>

                        <div class="form-group">
                            <label class="form-label">Mô tả</label>
                            <textarea asp-for="MoTa" class="form-control"></textarea>
                            <span asp-validation-for="MoTa" class="text-danger" />
                        </div>

                        <div class="form-group">
                            <label class="form-label">Trạng thái</label>
                            <select asp-for="TrangThai" class="form-control">
                                <option>--Chọn hiển thị</option>
                                <option value="1">Hiển thị</option>
                                <option value="0">Không hiển thị</option>

                            </select>
                            <span asp-validation-for="TrangThai" class="text-danger" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>

                        </div>
                    </form>
                    <a asp-action="index">Danh sách địa điểm </a>

                </div>
            </div>

        </div>
    </div>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/DanhMuc/Edit.cshtml
@model DanhMucModel
@{
    ViewData["title"] = "Cập nhật Danh mục";
}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 col-12 mx-auto">
            <div class="card mt-5">
                <div class="card-header">
                    <h3>Cập nhật Danh mục</h3>
                </div>
                <div class="card-body">
                    <form asp-action="Edit" asp-controller="DanhMuc" method="post">
                        <input type="hidden" asp-for="MaDanhMuc" />
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label class="form-label">Tên Danh mục</label>
                            <input asp-for="TenDanhMuc" type="text" class="form-control" />
                            <span asp-validation-for="TenDanhMuc" class="text-danger" />
                        </div>

                        <div class="form-group">
                            <label class="form-label">Mô tả</label>
                            <textarea asp-for="MoTa" class="form-control"></textarea>
                            <span asp-validation-for="MoTa" class="text-danger" />
                        </div>

                        <div class="form-group">
                            <label class="form-label">Trạng thái</label>
                            <select asp-for="TrangThai" class="form-control">
                                <option>--Chọn hiển thị</option>
                                <option value="1">Hiển thị</option>
                                <option value="0">Không hiển thị</option>

                            </select>
                            <span asp-validation-for="TrangThai" class="text-danger" />
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Cập nhật</button>

                        </div>
                    </form>
                    <a asp-action="index">Danh sách danh mục</a>

                </div>
            </div>

        </div>
    </div>

</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Areas/Admin/Views/DanhMuc/Index.cshtml
@model IEnumerable<DanhMucModel>
<main>
    <div class="container-fluid px-4">
        <h3 class="mt-4">Danh Sách danh mục</h3>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item"><a asp-action="Index"  asp-controller="QuanTri">Trang quản trị</a></li>
            <li class="breadcrumb-item active">Tables</li>
        </ol>
       
        <div class="card mb-4">
           
            <div class="card-body">
                <div class="datatable-wrapper datatable-loading no-footer sortable searchable fixed-columns">
                    <div class="card">
                        <h3><a asp-action="Create" asp-controller="DanhMuc" class="btn btn-primary">Thêm mới danh mục</a></h3>
                    </div>
                  
                    <div class="datatable-container">
                        <table id="myTable" class="table table-bordered">
                            <thead>
                                <tr>
                                    <th data-sortable="true" >
                                        #
                                    <th data-sortable="true">
                                         Tên Danh mục
                                        </th>
                                        <th data-sortable="true" >
                                          Slug Danh mục
                                            <th data-sortable="true" >Mô tả</th>
                                            <th data-sortable="true" >Trạng Thái</th>
                                            <th data-sortable="true">Manager</th>
                                            
                                        </tr>
                                        </thead>
                                            <tbody>
                                @foreach(var item in Model)
                                {
                                    <tr data-index="0">
                                        <td class="text-center align-middle">@item.MaDanhMuc</td>
                                        <td class="text-center align-middle">@item.TenDanhMuc</td>
                                        <td class="text-center align-middle">@item.SlugDanhMuc</td>
                                        <td class="text-center align-middle">@item.MoTa</td>

                                        @if (item.TrangThai ==1 )
                                        {
                                            <td>
                                                <button class="btn btn-primary">Hiển thị</button>
                                            </td>
                                        }
                                        else
                                        {
                                            <td class="text-center align-middile">
                                                <button class="btn btn-warning"> Không Hiển thị</button>
                                            </td>
                                        }
                                       
                                        <td>
                                            <a class="btn btn-warning" asp-action="Edit" asp-controller="DanhMuc" asp-route-Id="@item.MaDanhMuc">Edit</a>
                                            <a class="btn btn-danger" asp-action="Delete" asp-controller="DanhMuc" asp-route-Id="@item.MaDanhMuc">Delete</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                                                    </table>
                                                    </div>
                  
                </div>
            </div>
        </div>
    </div>
</main>
<